-- -- -- View all employees
-- SELECT
--     employees.id,
--     employees.first_name,
--     employees.last_name,
--     roles.title AS role,
--     departments.name AS department,
--     roles.salary,
--     CONCAT(managers.first_name, ' ', managers.last_name) AS manager
-- FROM
--     employees
--     LEFT JOIN roles ON employees.role_id = roles.id
--     LEFT JOIN departments ON roles.department_id = departments.id
--     LEFT JOIN employees AS managers ON employees.manager_id = managers.id;

-- -- View employees by manager
-- SELECT
--     employees.id,
--     employees.first_name,
--     employees.last_name,
--     roles.title AS role,
--     departments.name AS department,
--     roles.salary,
--     CONCAT(managers.first_name, ' ', managers.last_name) AS manager
-- FROM
--     employees
--     LEFT JOIN roles ON employees.role_id = roles.id
--     LEFT JOIN departments ON roles.department_id = departments.id
--     LEFT JOIN employees AS managers ON employees.manager_id = managers.id
-- WHERE
--     managers.id = [manager_id];

-- -- View employees by department
-- SELECT
--     employees.id,
--     employees.first_name,
--     employees.last_name,
--     roles.title AS role,
--     roles.salary,
--     CONCAT(managers.first_name, ' ', managers.last_name) AS manager
-- FROM
--     employees
--     LEFT JOIN roles ON employees.role_id = roles.id
--     LEFT JOIN employees AS managers ON employees.manager_id = managers.id
-- WHERE
--     roles.department_id = [department_id];

-- -- Calculate department budget
-- SELECT
--     departments.name AS department,
--     SUM(roles.salary) AS total_budget
-- FROM
--     departments
--     LEFT JOIN roles ON departments.id = roles.department_id
-- GROUP BY
--     departments.name;
